name = "metacognicao"
pages_build_output_dir = "dist"
compatibility_date = "2026-09-29"

[[d1_databases]]
binding = "DB"
database_name = "metacognicao-db"
database_id = "4be2b8c2-6034-4e7a-aed5-60a7f33fc108"

[ai]
binding = "AI"
